#!/bin/bash
#Setting a variable to track iterations of the loop (n). While loop is running so long as the value of n is less than or equal to 10. The while loop runs the cmd to display "Best School" for the line and adds 1 to n for each loop.
n=1
while [ $n -le 10 ]
do
	echo "Best School"
	((n++))
done
