#!/usr/bin/env bash
#n variable setup. while n is less than 10 do if n=9 echo Hi else echo Best School
n=0

while [ $n -le 10 ]
do
	echo "Best School"
	n=$(( n + 1 ))

       	if [ $n = 9 ]
	then	
		echo "Hi"
	fi

done
