#!/usr/bin/env bash
#n variable setup. while loop $n less than or equal to 20 does echo "$n" n=$((n++))
n=1
while [ $n -le 20 ]
do
	echo "$n"
	case $n in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((n++))
done

	
