#!/usr/bin/env bash
#the reason this works is because while loops only run so long as their conditions are true. so for ex. once the min
#reach 60 the while loop stops running then the hour variable gets incrimented. then when the original while loop
#starts again it will reset the min variable before going back into the minute while loop.
h=0
m=1
while [ $h -le 12 ]
do	
	echo "Hours: $h"
	
	while [ $m -le 59 ]
	do
		echo "$m"
		((m++))
	done
	((h++))
done
